modLoader = "javafml"
loaderVersion = "*"
license = "MIT"
issueTrackerURL = "https://www.curseforge.com/minecraft/mc-mods/collision-damage-port"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "fonnymunkey, Sxilverr"
description = "Adds acceleration-based collision damage to the player."
logoFile = "title.png"
credits = "Original mod by fonnymunkey, Ported to 1.20.1 and 1.21.1 by Sxilverr"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/collision-damage-port"

[[dependencies.${id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "*"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft}"
    ordering = "NONE"
    side = "BOTH"
